apiVersion: v1
kind: Pod
metadata:
  name: helloworld
spec:
  containers:
  - name: helloworld
    image: busybox
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "200Mi"
    command: ["sleep"]
    args: ["10000"]
